version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    volumes:
      - ./:/go/src
    command: go run ./cmd/main.go
    ports:
      - '3030:3000'
